add array support for metadata, fixes #4
zenstruck/class-metadata pull request #6
Opened 2024-11-13 12:17 UTC by tacman

I updated the docs, attribute and tests.

It got me thinking, though, if null should be allowed as a valid metadata value.

Nonetheless, I think this fixes #4

2024-11-13 12:55 UTC, tacman commented
I fixed the phpstan errors, except for one:

```bash
vendor/bin/phpstan
```

> ::error file=src/Metadata.php,line=22,col=0::Method Zenstruck\Metadata::__construct() has parameter $value with no value type specified in iterable type array.


```php
final class Metadata
{
    public function __construct(
        /** @readonly */
        public string $key,

        /**
         * @readonly
         * @param string|bool|int|float|mixed value
         */
        public string|bool|int|float|array $value,
    ) {
    }
```

What should this be?

2024-11-14 04:06 UTC, kbond requested changes
Looks good! I think my suggestions will fix phpstan.

> It got me thinking, though, if null should be allowed as a valid metadata value.

Couldn't hurt but maybe wait until someone needs it.

2024-11-14 04:06 UTC, kbond commented on src/Metadata.php
> +         * @param string|bool|int|float|mixed value
```suggestion
         * @param scalar|array<scalar> value
```

2024-11-14 04:06 UTC, kbond commented on src/Metadata.php
> +     * @return string|bool|int|float|array<mixed> value
```suggestion
     * @return scalar|array<scalar>|null
```

2024-11-14 04:06 UTC, kbond commented on src/Metadata.php
> +     * @return  string|bool|int|float|array<mixed>|null value
```suggestion
     * @return scalar|array<scalar>|null
```

2024-11-14 04:06 UTC, kbond commented on src/Metadata/Map.php
> +    /** @var array<string|class-string,array<string,scalar|mixed[]>> */
```suggestion
    /** @var array<string|class-string,array<string,scalar|array<scalar>>> */
```

2024-11-14 13:13 UTC, kbond commented
I'll take a look at fixing phpstan before merging.

2024-11-14 20:32 UTC, kbond approved these changes

2024-11-14 20:34 UTC, kbond commented
Thanks @tacman!

2024-11-14 20:34 UTC, merged